### ISSUE TITLE
Failed to install op25 on kali linux ( Nethunter )

### ISSUE THREAD

**Issue by khanfar** [boatbod/op25#100]
Hi , when i try to install op25 on kali linux nethunter using this command  ./install.sh i got this error in attached picture below , please any help 
![Screenshot_20210130-061058220](https://user-images.githubusercontent.com/16803586/106354763-d0d78d00-62fc-11eb-816a-fe13148d6cfe.jpg)

**Comment by khanfar** [comment]
(( This is CMake Error.log ))


![Screenshot_20210130-132807031](https://user-images.githubusercontent.com/16803586/106355330-ce2a6700-62ff-11eb-86e2-759765e5d044.jpg)

**Comment by khanfar** [comment]
(( This is CMake Output.log  ))

![Screenshot_20210130-133242211](https://user-images.githubusercontent.com/16803586/106355370-0b8ef480-6300-11eb-8f2c-26185b70a160.jpg)

**Comment by boatbod** [comment]
From the error with FindTHRIFT.cmake I assume your version of kali is running gnuradio 3.8.2?
For reasons best known to the GR developers there were changes made in the gnuradio cmake scripts which force the incorporation of the "THRIFT" module, but for some reason FindTHRIFT is not properly including GrPython so the script fails.

I haven't yet found a good solution that doesn't break earlier versions, but as a workaround you can edit the FindTHRIFT.cmake file (found under the /usr/lib hierachy)  and place "include(GrPython)" on the first line then re-run the cmake and it should work.

**Comment by boatbod** [comment]
I found and implemented a fix for the FindTHRIFT / GrPython cmake problem in gnuradio-3.8.2
