### ISSUE TITLE
List of neighboring sites

### ISSUE THREAD

**Issue by VVakko** [boatbod/op25#104]
In my location, the frequency of control channels for some sites changes every day or two. I would like to try to automate the process of collecting actual frequencies. How can I programmatically get information about neighboring sites by tuning in to receive the control channel of a known site?
How DSD+ does it (see screenshots).
![Example #1](https://i.ytimg.com/vi/260eprJ9M-Y/maxresdefault.jpg)
![Example #1](https://i.redd.it/s9uaxmb1uxgz.jpg)

**Comment by boatbod** [comment]
Probably not the most convenient, but if you turn logging up to '-v 11' you should see some messages for "adjacent:".
02/09/21 07:28:50.908052 [0] tsbk3c adjacent: rfid 3 stid 8 ch1 1712(773.318750)
02/09/21 07:28:51.245612 [0] tsbk3c adjacent: rfid 3 stid 11 ch1 17ae(774.293750)
02/09/21 07:28:51.541868 [0] tsbk3c adjacent: rfid 3 stid 12 ch1 1642(772.018750)
