### ISSUE TITLE
recover information from a running rx.py instance

### ISSUE THREAD

**Issue by JonaldJohnston** [boatbod/op25#111]
hello!
I want to script a nice display for my P25 scanner and I was wondering what is a good way to grab data (frequencies, active TGs, etc.) from a running instance of rx.py? currently i have just been using `-v 10` and processing the data from stderr in a python script, but it's not very "complete" and seems very cumbersome.

**Comment by boatbod** [comment]
OP25 already supports a basic http-based gui. It could do with being made a lot better, but the basics are there, and more importantly everything you asked about (frequencies, active tgs, ...) is already parse-able from the JSON data structure that is sent in response to the http-get.
