### ISSUE TITLE
Help , How to monitor two control frequency at the same time ??

### ISSUE THREAD

**Issue by khanfar** [boatbod/op25#12]
I edit trunk.tsv and add two system name and two frequency  and offset 0 and nac and modulation  and chose .tompkins.tsv for tgid tag file , i chose this tag file for two control frequency,  but when i run software in terminal i put just -f 846.2600e6 , does this correct ???? and -t trunk.tsv , but it not go to next monitor frequency! It still in main first frequency,  whats wrong ????? Should i need to put in -f two frequencies??? Or whats wrong ??? Its still in first frequency?????.
My command like this : 
./rx.py --args 'rtl' -N 'LNA:47' -S 2400000 -f 846.2600e6 -o 25000 -q 15 -2 -T trunk.tsv -V -2 -U 2> stderr.2

Any wrong in my command  ??????

**Comment by boatbod** [comment]
To monitor more than one system you have to have fully specified trunk.tsv with non-zero NACs on each line.  System will monitor one control channel then switch to the other after 3 seconds.  Any conversations in progress will cause the system to hold until the conversation completes.
