### ISSUE TITLE
Is there way to record active voice ???

### ISSUE THREAD

**Issue by khanfar** [boatbod/op25#13]
Is there way to record active voice? and active frequency history log ?

**Comment by boatbod** [comment]
tgid/freq log can be achieved by turning logging up to "-v 1" then look in the log for "voice update" entries.

Unfortunately there really isn't a way to record the voice unless you use an application such as liquidsoap to archive to file as well as sending to the audio subsystem.

**Comment by khanfar** [comment]
Please is there instructions how to figure liquidsoap with op25 ?

**Comment by khanfar** [comment]
You mean add -v 1 to ./rx.py --args .... command ? Were should i see the
log file location ?

**Comment by khanfar** [comment]
i try to use installation liquidsoap.sh from this link : https://gist.github.com/dtcooper/a1a9d6b1b96a01191514cfbb425e5f35
but in final installation on my ubuntu 18.04 i got this error :
W: Not_found
W: Not_found
E: Cannot find external tool 'ocamlbuild'
E: Failure("1 configuration error")

please give us how use this and install with op25
