### ISSUE TITLE
OP25 plot makes RPi lose CC

### ISSUE THREAD

**Issue by JoeyAbsi** [boatbod/op25#136]
When running at least 1 plot, Raspberry Pi (3 B+) loses the CC and starts the CC hunting.

RPi cpu is running at 20 % (normally) and 35-40% when running 1 plot which makes it odd to lose the CC.

*I am running OP25's multi_rx.py script.

EDIT: I am having the same issue when running OP25 on Ubuntu (on a vm).

**Comment by boatbod** [comment]
Plots require considerable cpu - try running the sample rate at -S 1000000 (the practical minimum).  Recommend not leaving plots running unless you are actively using them.
