### ISSUE TITLE
Feature Request: Unscramble DMR Hytera Basic Encrypt using Key

### ISSUE THREAD

**Issue by Nokoa** [boatbod/op25#142]
Feature for DMR decryption of basic encrypt (BP) for Hytera series radios. User will input key in config. Motorola BP already appears to be supported using XOR. Hytera's slightly differs. 10, 32, and 64 character keys, not sure what the algorithm is for the scrambling. According to Hytera it's supposed to be a simple mathematical algorithm.

**Comment by boatbod** [comment]
Without knowing the Hytera algorithm I have insufficient information to implement the unscrambling.
