### ISSUE TITLE
OP25 web server

### ISSUE THREAD

**Issue by DanielAbsi** [boatbod/op25#145]
Hi, I have a Raspberry PI running OP25. I want to setup to PI to a load balancer (KEMP).

Then I forward the OP25 port on Kemp kemp tells me that OP25 off. I was wondering. All of my services are working well except OP25. 

After  a bit of troubleshooting, I was wondering if OP25 have a web server (Apache, Nginx)

Thanks.

**Comment by boatbod** [comment]
OP25 has a very rudimentary web server based on Python Waitress.  Since it has ZERO (none, nada, zip,...) security, I strongly do not recommend you expose this to the outside world.
