### ISSUE TITLE
New Build Help

### ISSUE THREAD

**Issue by c73martin** [boatbod/op25#146]
I recently tried to get a op25 running on pi 3b+, I am going to paste a copy of Stder file, but I seem to be way off Freq from Radio Reference control channels.  I attempted to use GQRX and locate the highest peaked channel in the vicinity and was able to get a lock and list of voice channels but no audio and see the system does lose control channel due to a time out. Any help would be greatly appreciated. I also am unable to get any audio but assume that is due to poor setup.

Using Python /usr/bin/python3
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
gain: name: LNA range: start 0 stop 0 step 0
setting gain LNA to 47
supported sample rates 250000-2560000 step 24000
[R82XX] PLL not locked!
Using two-stage decimator for speed=960000, decim=10/4 if1=96000 if2=24000
op25_audio::open_socket(): enabled udp host(127.0.0.1), wireshark(23456), audio(23456)
p25_frame_assembler_impl: do_imbe[1], do_output[0], do_audio_output[1], do_phase2_tdma[1], do_nocrypt[1]
metadata update not enabled
using ALSA sound system
audio device: default
Listening on 127.0.0.1:23456
python version detected: 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110]
Allocating 15 zero-copy buffers
02/15/22 09:50:56.070593 control channel timeout
02/15/22 09:50:56.643378 voice update:  tg(563), freq(774156250), slot(-), prio(3)
02/15/22 09:50:58.664337 voice update:  tg(563), freq(774156250), slot(-), prio(3)
02/15/22 09:51:01.140626 voice update:  tg(563), freq(851600000), slot(-), prio(3)
02/15/22 09:51:03.186898 voice update:  tg(563), freq(851600000), slot(-), prio(3)
02/15/22 09:51:05.228297 voice update:  tg(563), freq(851600000), slot(-), prio(3)
02/15/22 09:51:07.144054 voice update:  tg(563), freq(851600000), slot(-), prio(3)
02/15/22 09:51:08.924792 voice update:  tg(563), freq(851600000), slot(-), prio(3)
02/15/22 09:51:11.108829 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:51:13.154454 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:51:15.195683 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:51:17.243648 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:51:19.284971 voice update:  tg(537), freq(851600000), slot(-), prio(3)
02/15/22 09:51:21.480747 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:51:23.670753 voice update:  tg(537), freq(851600000), slot(-), prio(3)
02/15/22 09:51:25.712781 voice update:  tg(537), freq(851600000), slot(-), prio(3)
02/15/22 09:51:28.172799 voice update:  tg(1175), freq(852925000), slot(1), prio(3)
02/15/22 09:51:31.339671 voice update:  tg(537), freq(851450000), slot(-), prio(3)
02/15/22 09:51:33.479417 voice update:  tg(711), freq(773218750), slot(-), prio(3)
02/15/22 09:51:35.811228 voice update:  tg(563), freq(851600000), slot(-), prio(3)
02/15/22 09:51:37.871393 voice update:  tg(541), freq(774156250), slot(-), prio(3)
02/15/22 09:51:39.513911 voice update:  tg(541), freq(774156250), slot(-), prio(3)
02/15/22 09:51:42.232105 voice update:  tg(1175), freq(853125000), slot(0), prio(3)
02/15/22 09:51:44.301341 voice update:  tg(537), freq(852925000), slot(-), prio(3)
02/15/22 09:51:46.343931 voice update:  tg(537), freq(852925000), slot(-), prio(3)
02/15/22 09:51:48.526880 voice update:  tg(1175), freq(853125000), slot(0), prio(3)
02/15/22 09:51:50.149375 voice update:  tg(1175), freq(853125000), slot(0), prio(3)
02/15/22 09:51:51.782422 voice update:  tg(1175), freq(853125000), slot(0), prio(3)
02/15/22 09:51:53.436487 voice update:  tg(1175), freq(853125000), slot(0), prio(3)
02/15/22 09:51:55.757807 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:51:57.781204 voice update:  tg(1155), freq(852925000), slot(-), prio(3)
02/15/22 09:51:59.990778 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:01.908295 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:04.078351 voice update:  tg(1155), freq(774156250), slot(-), prio(3)
02/15/22 09:52:06.136824 voice update:  tg(2673), freq(853125000), slot(1), prio(3)
02/15/22 09:52:07.779826 voice update:  tg(2673), freq(853125000), slot(1), prio(3)
02/15/22 09:52:09.402408 voice update:  tg(2673), freq(853125000), slot(1), prio(3)
02/15/22 09:52:11.714698 voice update:  tg(697), freq(774156250), slot(-), prio(3)
02/15/22 09:52:13.631930 voice update:  tg(697), freq(774156250), slot(-), prio(3)
02/15/22 09:52:15.812968 voice update:  tg(1155), freq(771981250), slot(-), prio(3)
02/15/22 09:52:18.288990 voice update:  tg(527), freq(852925000), slot(-), prio(3)
02/15/22 09:52:20.512021 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:22.503347 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:24.564594 voice update:  tg(527), freq(851600000), slot(-), prio(3)
02/15/22 09:52:26.745070 voice update:  tg(527), freq(851600000), slot(-), prio(3)
02/15/22 09:52:29.048103 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:30.981482 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:33.164224 voice update:  tg(711), freq(851450000), slot(-), prio(3)
02/15/22 09:52:35.336094 voice update:  tg(711), freq(851600000), slot(-), prio(3)
02/15/22 09:52:37.389850 voice update:  tg(2218), freq(851450000), slot(-), prio(3)
02/15/22 09:52:39.449126 voice update:  tg(697), freq(852925000), slot(-), prio(3)
02/15/22 09:52:41.478065 voice update:  tg(527), freq(851450000), slot(-), prio(3)
02/15/22 09:52:43.535247 voice update:  tg(527), freq(851450000), slot(-), prio(3)
02/15/22 09:52:46.135892 voice update:  tg(883), freq(771981250), slot(0), prio(3)
02/15/22 09:52:47.761173 voice update:  tg(883), freq(771981250), slot(0), prio(3)
02/15/22 09:52:49.945660 voice update:  tg(729), freq(771981250), slot(1), prio(3)
02/15/22 09:52:51.593690 voice update:  tg(729), freq(771981250), slot(1), prio(3)
02/15/22 09:52:53.766268 voice update:  tg(719), freq(851600000), slot(-), prio(3)
02/15/22 09:52:55.813416 voice update:  tg(719), freq(851600000), slot(-), prio(3)
02/15/22 09:52:57.728509 voice update:  tg(719), freq(851600000), slot(-), prio(3)
02/15/22 09:52:59.786478 voice update:  tg(1155), freq(851450000), slot(-), prio(3)
02/15/22 09:53:01.833208 voice update:  tg(1155), freq(851450000), slot(-), prio(3)
02/15/22 09:53:03.872301 voice update:  tg(651), freq(851600000), slot(-), prio(3)
02/15/22 09:53:06.071528 voice update:  tg(883), freq(852925000), slot(1), prio(3)
02/15/22 09:53:07.977765 voice update:  tg(883), freq(852925000), slot(1), prio(3)
02/15/22 09:53:10.703492 voice update:  tg(883), freq(852925000), slot(0), prio(3)
02/15/22 09:53:12.607169 voice update:  tg(883), freq(852925000), slot(0), prio(3)
02/15/22 09:53:15.093478 voice update:  tg(651), freq(851450000), slot(-), prio(3)
02/15/22 09:53:17.277288 voice update:  tg(651), freq(851450000), slot(-), prio(3)
02/15/22 09:53:19.154264 voice update:  tg(651), freq(851450000), slot(-), prio(3)
02/15/22 09:53:21.750695 control channel timeout
02/15/22 09:53:21.768273 voice update:  tg(725), freq(771981250), slot(-), prio(3)
02/15/22 09:53:24.339748 control channel timeout
02/15/22 09:53:25.432963 control channel timeout
02/15/22 09:53:25.590632 voice update:  tg(2013), freq(853125000), slot(-), prio(3)
02/15/22 09:53:27.630290 voice update:  tg(931), freq(851600000), slot(-), prio(3)
02/15/22 09:53:30.620863 control channel timeout
02/15/22 09:53:31.713106 control channel timeout
02/15/22 09:53:33.486923 control channel timeout
02/15/22 09:53:34.055329 voice update:  tg(651), freq(851450000), slot(-), prio(3)
02/15/22 09:53:35.963194 voice update:  tg(651), freq(851450000), slot(-), prio(3)
02/15/22 09:53:38.950875 voice update:  tg(651), freq(851450000), slot(-), prio(3)
02/15/22 09:53:41.007064 voice update:  tg(883), freq(771981250), slot(0), prio(3)
02/15/22 09:53:43.066957 voice update:  tg(883), freq(771981250), slot(0), prio(3)
02/15/22 09:53:45.652214 voice update:  tg(563), freq(851450000), slot(-), prio(3)
02/15/22 09:53:47.834978 voice update:  tg(563), freq(851450000), slot(-), prio(3)
02/15/22 09:53:49.895172 voice update:  tg(711), freq(851600000), slot(-), prio(3)
02/15/22 09:53:53.012316 control channel timeout
02/15/22 09:53:54.650194 control channel timeout
02/15/22 09:53:55.907507 voice update:  tg(719), freq(851600000), slot(-), prio(3)
02/15/22 09:53:57.927675 voice update:  tg(2013), freq(851450000), slot(-), prio(3)
02/15/22 09:54:00.110668 control channel timeout
02/15/22 09:54:01.764686 voice update:  tg(563), freq(773218750), slot(-), prio(3)
02/15/22 09:54:04.491475 voice update:  tg(709), freq(852925000), slot(0), prio(3)
02/15/22 09:54:08.576794 control channel timeout
02/15/22 09:54:09.668888 control channel timeout
02/15/22 09:54:11.033609 control channel timeout
02/15/22 09:54:12.127687 control channel timeout
02/15/22 09:54:13.902255 control channel timeout
02/15/22 09:54:14.319839 voice update:  tg(711), freq(851600000), slot(-), prio(3)
02/15/22 09:54:16.494391 control channel timeout
main: exception occurred
main: exception:
Traceback (most recent call last):
  File "/home/pi/op25/op25/gr-op25_repeater/apps/./rx.py", line 997, in run
    time.sleep(1)
KeyboardInterrupt

**Comment by boatbod** [comment]
By default op25 assumes a cqpsk compliant modulation since this is the most commonly seen variant in use.  Some stand-along (non-simulcast) P25 FDMA (phase 1only) systems have c4fm modulation that doesn't play well with the default demodulator and under these circumstances you might try using "-D fsk4" on your rx.py command line.
