### ISSUE TITLE
Plots not working

### ISSUE THREAD

**Issue by kbbj0197** [boatbod/op25#147]
Not an issue persay, but a query: what libraries are required to operate plots? op25 worked well under Ubuntu-16, but now using more restricted Linux version without multiple unneeded files/libraries. Currently op25 starts up, but will not call up any plots when #s are selected.

**Comment by kbbj0197** [comment]
I received help on RadioReference.com:

The problem was that the app makes a call for the "gnuplot" file, but I did not have that file link. It was only listed as gnuplot4-xll with the links gnuplot and gnuplot4 linked to nothing. I relinked these to the gnuplot4-xll file and all works as advertised again. So I had all the libraries, but not properly referenced.

Thank you.

**Comment by boatbod** [comment]
op25 assumes there is an executable called '/usr/bin/gnuplot'.  The minimum package install is gnuplot-x11
