### ISSUE TITLE
How to select specific sdr to run on op25 when i connect two sdr on pc ? 

### ISSUE THREAD

**Issue by khanfar** [boatbod/op25#15]
How to selectsdr sn : 001 to run on op25 when i have connect two sdr at the same pc ? The sdr two sn : 002 , and can i run two sdr at the same time ??? and how ?

**Comment by tarantir** [comment]
You specify that with the rtl parameter e.g.

rtl=0 set to rtl=1

**Comment by khanfar** [comment]
Thanks
