### ISSUE TITLE
Feature Request: Access error count from SWIG'd code

### ISSUE THREAD

**Issue by MattMills** [boatbod/op25#152]
Hello,

I was thinking about opening a PR for this, but since I'm a below average C++ programmer at best, I figured I'd make a feature request instead.

My code (https://github.com/MattMills/radiocapture-rf) uses op25 in a more "batch" mode, where an p25_frame_assembler is used to decode an individual call, and then torn down. I added some functionality in my version of OP25 so that I could access error counts within voice decoding code and use that to prioritize the audio when there are multiple of the same transmission received (from multiple transmit sites of the same system). 

I see you have stderr output for tracking error count, but could you add a ::get_error_count or some such for accessing the count programmatically?

Thanks,
Matt.

**Comment by boatbod** [comment]
It would be possible but then you'd also have to track the error counts within the protocol object, and for them to be meaningful you'd also have to track the total number of bits received or a BER estimate.  Lastly, you'd probably want to avoid a polling interface and look more towards gnuradio's message passing and callback/registration process.
