### ISSUE TITLE
frequency is not the same on web interface and cannot be changed 

### ISSUE THREAD

**Issue by awipslinuxuser** [boatbod/op25#153]
so i have my local fire station  154.41500  programmed into op25 but when i launch the web interface its sho
![Screenshot 2022-05-15 170814](https://user-images.githubusercontent.com/67390756/168496140-1618788d-0b6b-4958-8898-09a1a799da34.png)
![Screenshot 2022-05-15 170936](https://user-images.githubusercontent.com/67390756/168496143-f835431f-7256-4174-8af0-cb3b9d61ab9a.png)
wing this frequency 0.000154 and i cannot change the frequency but it should be the same as from the terminal is

**Comment by awipslinuxuser** [comment]
and yes i have tried to use skip and the arrows but the frequency didn't change

**Comment by thetoivonen** [comment]
Input frequency in Hz not MHz so change to 154.415e6
