### ISSUE TITLE
Priority clarificiation in the tgid-tags.tsv

### ISSUE THREAD

**Issue by djkraven** [boatbod/op25#154]
I am using the priority option in the tgid-tags.tsv file and have some questions.
 1.  What is the valid range ex: 0-9?
 2. Priority 0 will take priority over priority 3?
 3. If priority is used does it need to be on each entry or just the ones that are different from the default of 3?

**Comment by JoeyAbsi** [comment]
Valid range is 0-5
The lower the number is, the higher the priority (priority 0 is a higher priority than 3)
If nothing is added for the priority, it will be 3 by default

**Comment by boatbod** [comment]
Valid range is ANY integer number
Lower number takes priority over higher number
Default value if priority is unspecified is 3
