### ISSUE TITLE
decrypt dmr 

### ISSUE THREAD

**Issue by romanremus** [boatbod/op25#166]
hello Boatbod ..... in my country I can only enjoy a few dmr signals ... which are clear and have a very rare activity, but the other dmr signals that have a permanent activity are with AD RC4, being a radio amateur I'm listening.....please, do you think you can make it work on windows too??? or can it be added to dsd somehow. or how can I use your software??? thank you very much

**Comment by boatbod** [comment]
You could consider running ubuntu in a virtual machine under windows, but there's no way for me to do a native port of op25 into a windows environment.

**Comment by romanremus** [comment]
How can comand for start dmr witch key RC4 ?.....thanks 
    Pe luni, 9 ianuarie 2023, 05:11:38 EET, boatbod ***@***.***> a scris:  
 
 


You could consider running ubuntu in a virtual machine under windows, but there's no way for me to do a native port of op25 into a windows environment.
