### ISSUE TITLE
possible additional size issues

### ISSUE THREAD

**Issue by ZeroChaos-** [boatbod/op25#174]
I opened this bug for trunk-radio which uses a forked op25.  I suspect it applies to you both but I haven't had a chance to test op25 and I don't understand the code well enough to check it manually.
https://github.com/robotastic/trunk-recorder/issues/783

**To Reproduce**
1. compile with -D_GLIBCXX_ASSERTIONS in CXXFLAGS
2. run the result
3. wait a little while

**System Information (please complete the following information):**
 - OS: Gentoo
 - GNURadio version: 3.10.5.1
 - GCC version: 12.2.1

**Additional context**
Issue is similar to those fixed by https://github.com/boatbod/op25/pull/173

**Comment by boatbod** [comment]
Looks like DMR? Could you elaborate on the scenario or at least the type 
of system being monitored?
Thanks,
Graham
