### ISSUE TITLE
Talkgroup Delay

### ISSUE THREAD

**Issue by edmk5000** [boatbod/op25#185]
A "talkgroup Delay" would help when activity on talkgroup might have a "response."

Currently, during scanning multiple talkgroups, as soon as a talkgroup stops transmitting, scanning resumes. You may miss a response on the talkgroup that was previously tuned to if it transmits again quickly.

This would be the same "delay" feature scanners have.

A command like -y seconds and/or tsv setting would be great.

-y seconds to stay on talkgroup]

Ex.
-y2 would wait on current talkgroup for 2 seconds

DELAY "2" would wait on current talkgroup for 2 seconds.

**Comment by boatbod** [comment]
rx.py and multi_rx.py already both have TGID_HOLD_TIMER at 2.0 seconds.
