### ISSUE TITLE
Help ... How to run normal airspy ? whats command and setting should i type ?

### ISSUE THREAD

**Issue by khanfar** [boatbod/op25#19]

**Comment by ksquared64** [comment]
On Linux I am using:  ./rx.py --args 'airspy' -N 'LNA:8,MIX:5,IF:15' -S 2500000 -x 2 -f 850.1235e6 -q -11 -T trunk.tsv -V -2 -U 2> stderr.2

This is running very well in an Ubuntu 16.04 LTS VM under Parallels on Mac OSX
