### ISSUE TITLE
Feature: Whitelist/Blacklist command line flags

### ISSUE THREAD

**Issue by n0mo** [boatbod/op25#20]
It would be helpful to be able to load whitelists or blacklists from the command line instead of creating new trunk.tsv files for different listening activities.

**Comment by boatbod** [comment]
While I agree in principle that more dynamic control of config is necessary, I am moving away from using (exceessively complicated) command line parameters and rx.py development is primarily maintenance-only in nature.  New features are being focused on multi_rx.py which is configured from .json file. 

At this point it is possible to have op25 reload the contents of the blacklist/whitelist files dynamically by invoking the appropriate terminal command.
