### ISSUE TITLE
Talk group patching not supported p25p2

### ISSUE THREAD

**Issue by Nokoa** [boatbod/op25#26]
I was monitoring a police talk group on a p25p2 system. Then they needed to communicate with another department on a county wide mutual aid talk group during an incident. So dispatch "patched" them in to that other talk group which is within that same system and all communications actually took place on the mutual aid talk group. Op25 wouldn't receive anything because I don't have that talk group whitelisted. But my uniden scanners were still able to receive all radio traffic and would display the original talkgroup id.  Once I whitelisted the mutual aid talkgroup on op25 it would receive it fine, but I can't keep it like that because other departments can also use it.

**Comment by boatbod** [comment]
Patches are now supported (as of Sept/Oct 2019)
