### ISSUE TITLE
TGID TAG not showiing up in web interface

### ISSUE THREAD

**Issue by neuronet77** [boatbod/op25#30]
In the web interface coming with OP25 the TGID TAG is not being sent via the json.

in trunking.py 

    def to_json(self):
        d = {}
        d['syid'] = self.rfss_syid
        d['rfid'] = self.rfss_rfid
        d['stid'] = self.rfss_stid
        d['sysid'] = self.ns_syid
        d['rxchan'] = self.rfss_chan
        d['txchan'] = self.rfss_txchan
        d['wacn'] = self.ns_wacn
        d['secondary'] = self.secondary.keys()
        d['tsbks'] = self.stats['tsbks']
        d['frequencies'] = {}
        d['frequency_data'] = {}
        d['last_tsbk'] = self.last_tsbk
        t = time.time()
        for f in self.voice_frequencies.keys():
            self.voice_frequencies[f]['tgid'][1] = self.get_tag(self.voice_frequencies[f]['tgid'][0]);
            tgs = '%s %s' % (self.voice_frequencies[f]['tgid'][0], self.voice_frequencies[f]['tgid'][1])
            d['frequencies'][f] = 'voice frequency %f tgid(s) %s %4.1fs ago count %d' %  (f / 1000000.0, tgs, t - self.voice_frequencies[f]['time'], self.voice_frequencies[f]['counter'])

            d['frequency_data'][f] = {'tgids': self.voice_frequencies[f]['tgid'], 'last_activity': '%7.1f' % (t - self.voice_frequencies[f]['time']), 'counter': self.voice_frequencies[f]['counter']}
	d['adjacent_data'] = self.adjacent_data
        return json.dumps(d)

added the line

`        self.voice_frequencies[f]['tgid'][1] = self.get_tag(self.voice_frequencies[f]['tgid'][0]);`

to ensure TGID TAG gets sent to the web client.

**Comment by DigiWhale** [comment]
Found the same issue except i was trying to output the Id to the command line so i could see it in the history.

```
def to_json(self):
        d = {}
        d['syid'] = self.rfss_syid
        d['rfid'] = self.rfss_rfid
        d['stid'] = self.rfss_stid
        d['sysid'] = self.ns_syid
        d['rxchan'] = self.rfss_chan
        d['txchan'] = self.rfss_txchan
        d['wacn'] = self.ns_wacn
        d['secondary'] = list(self.secondary.keys())
        d['tsbks'] = self.stats['tsbks']
        d['frequencies'] = {}
        d['frequency_data'] = {}
        d['last_tsbk'] = self.last_tsbk
        t = time.time()
        for f in list(self.voice_frequencies.keys()):
            tgs = '%s %s' % (self.voice_frequencies[f]['tgid'][0], self.voice_frequencies[f]['tgid'][1])
            d['frequencies'][f] = 'voice frequency %f Unit Name %s tgid(s) %s %4.1fs ago count %d' %  (f / 1000000.0, self.get_tag(self.voice_frequencies[f]['tgid'][0]), tgs, t - self.voice_frequencies[f]['time'], self.voice_frequencies[f]['counter'])

            d['frequency_data'][f] = {'tgids': self.voice_frequencies[f]['tgid'], 'last_activity': '%7.1f' % (t - self.voice_frequencies[f]['time']), 'counter': self.voice_frequencies[f]['counter']}
        d['adjacent_data'] = self.adjacent_data
        return json.dumps(d)
```
I changed this line and it now shows the "Unit Name" in the call history. I used the self.get_tag() function and injected the result into the CLI printed string.
```
d['frequencies'][f] = 'voice frequency %f Unit Name %s tgid(s) %s %4.1fs ago count %d' %  (f / 1000000.0, self.get_tag(self.voice_frequencies[f]['tgid'][0]), tgs, t - self.voice_frequencies[f]['time'], self.voice_frequencies[f]['counter'])
```
P.S. This is my first comment on github so hopefully i posted correctly.
