### ISSUE TITLE
Runing OP25 from rtl_tcp source !

### ISSUE THREAD

**Issue by khanfar** [boatbod/op25#43]
is there way to runing op25 from rtl_tcp ? through lan ?
Not physically connect SDR to pc to run op25 , Running it through lan rtl_tcp connected .
is that available ???? or can do it in future update ????

**Comment by boatbod** [comment]
I'm pretty sure you can just use rtl_tcp as-is.
https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr#rtl_tcp

Device string example:
"rtl_tcp=192.168.100.50:1234"
