### ISSUE TITLE
Files built without respecting CFLAGS

### ISSUE THREAD

**Issue by blshkv** [boatbod/op25#48]
```
 * QA Notice: Files built without respecting CFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/bin/BER
 * /usr/bin/scan4sync
 * /usr/lib/python3.7/site-packages/op25_repeater/_op25_repeater_swig.so
 * /usr/lib64/libgnuradio-op25.so
```

CMakefile need to be fixed

**Comment by blshkv** [comment]
The required flags are getting overwrite in the following line:
https://github.com/boatbod/op25/blob/master/CMakeLists.txt#L4

You can either drop it, or append them properly:
SET( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} blah" )

**Comment by boatbod** [comment]
Fixed
