### ISSUE TITLE
Python modules that are not byte-compiled

### ISSUE THREAD

**Issue by blshkv** [boatbod/op25#49]
```
 * 
 * This package installs one or more Python modules that are not byte-compiled.
 * The following files are missing:
 * 
 *   /usr/lib/python3.7/site-packages/op25_repeater/__pycache__/__init__.cpython-37.pyc
 *   /usr/lib/python3.7/site-packages/op25_repeater/__pycache__/__init__.cpython-37.opt-1.pyc
 *   /usr/lib/python3.7/site-packages/op25_repeater/__pycache__/__init__.cpython-37.opt-2.pyc
 *   /usr/lib/python3.7/site-packages/op25_repeater/__pycache__/op25_repeater_swig.cpython-37.pyc
 *   /usr/lib/python3.7/site-packages/op25_repeater/__pycache__/op25_repeater_swig.cpython-37.opt-1.pyc
 *   /usr/lib/python3.7/site-packages/op25_repeater/__pycache__/op25_repeater_swig.cpython-37.opt-2.pyc
 *   /usr/lib/python3.7/site-packages/op25/__pycache__/__init__.cpython-37.pyc
 *   /usr/lib/python3.7/site-packages/op25/__pycache__/__init__.cpython-37.opt-1.pyc
 *   /usr/lib/python3.7/site-packages/op25/__pycache__/__init__.cpython-37.opt-2.pyc
 * 
 * Please either fix the upstream build system to byte-compile Python modules
 * correctly, or call python_optimize after installing them.  For more
 * information, see:
 * https://wiki.gentoo.org/wiki/Project:Python/Byte_compiling

```

**Comment by boatbod** [comment]
I've no idea how cpython-37 gets made as it does not exist in my build tree.  Presumably it's unique to python3 which itself is largely an unknown until we get some ubuntu distros using it as standard.

Happy to look at a patch that might fix this, but as it stands there's not much I can do for you.

**Comment by blshkv** [comment]
You should be able to reproduce with any python3

**Comment by boatbod** [comment]
Actually it's not quite that simple.  You need a complete system built around python3 rather than python2 in order for the build tools and cmake stuff to work properly.  Just having python3 installed on (for example) ubuntu-16.04 does not help.

**Comment by blshkv** [comment]
can you go to the link which I send and check how to enable it? It should be as simple as adding "-m compileall"

**Comment by boatbod** [comment]
I left this open for a while in case I experienced any issues with byte compiling, but I have yet to experience any.  Python is supposed to byte-compile on an as-needed basis.
