### ISSUE TITLE
Feature: Lock down web gui

### ISSUE THREAD

**Issue by s3m1s0n1c** [boatbod/op25#5]
Would be nice to be able to lock down web gui with a username and password to stop unauthorized people accessing web gui.

Thanks

**Comment by khanfar** [comment]
How to acsess web gui for op25 ? And whats can i see there ?

**Comment by khanfar** [comment]
Is there way to make audio come through web GUI ???

**Comment by s3m1s0n1c** [comment]
> How to acsess web gui for op25 ? And whats can i see there ?

add ``-l http:0.0.0.0:8080`` to your syntax for rx.py
eg ``./rx.py --args "rtl=2" -S 2400000 -v 1 -2 -T cc.tsv -V -n -U -M meta.json -l http:0.0.0.0:8080 -N 'lna:29' ``


> Is there way to make audio come through web GUI ???
No there is no audio passed thru the web gui.. You would have to use ya speaker or stream it to an icecast server.

**Comment by khanfar** [comment]
Thanks for info , but how to record log of active frequency and were i can
find it ?

**Comment by hayden-t** [comment]
this would be easy, i can look into it

**Comment by boatbod** [comment]
Current gui has ZERO security.  Probably needs rewriting from scratch to make this feasible.
