### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by spencerhusak** [boatbod/op25#66]
I can not seem to be able to get audio through bluetooth and laggy audio

**Comment by JoeyAbsi** [comment]
On what are you running OP25 (RPI, Ubuntu...) and is your bluetooth speaker charged, connected?
If you try to play a video on YouTube do you still have this problem?

**Comment by spencerhusak** [comment]
I got it to all connect and work but i want it to auto start when the
system boots up and after it connects to the bluetooth im on raspberry pi
4. Before i had it auto starting via modifying the /etc/rc.local file but
op25 would boot before it was connected to bluetooth and than was using the
default audio via 3.5mm jack not bluetooth any suggestions

**Comment by JoeyAbsi** [comment]
OK so if I understood what you wrote, you are auto-starting OP25 on a RPI4 and want it to transmit its audio to a bluetooth speaker.
If you try to listen to the audio through the audio jack, is the audio good? 
If so, is the audio good on the bluetooth speaker while playing a YouTube video for example? 
Have you tried using another speaker to check if it works any better?

**Comment by spencerhusak** [comment]
My question is do i run op25 via op25.sh or manual mode?

**Comment by JoeyAbsi** [comment]
They both work great but it's way easier to run it via the OP25.sh file.

**Comment by spencerhusak** [comment]
Now its running perfect via the op25.sh file i had no clue about that took
a little bit of digging

**Comment by spencerhusak** [comment]
So the question is how to i get the op25.sh file to boot at start up

**Comment by JoeyAbsi** [comment]
I created a service:
The file is: /etc/systemd/system/op25-stream0.service (you can name it whatever you want though). 

Write this code in the service file:
[Unit]
Description=op25-ncshp
After=syslog.target network.target nss-lookup.target network-online.target
Requires=network-online.target

[Service]
User=pi
Group=pi
WorkingDirectory=/home/pi/op25/       //Make sure to select the right directory!
ExecStart=/bin/bash -- op25.sh
RestartSec=5
Restart=on-failure

[Install]
WantedBy=multi-user.target


Save this file and write the following code in the terminal:
sudo systemctl daemon-reload
sudo systemctl start OP25.service    //Or whatever your service name is...
sudo systemctl status OP25.service


This worked for me and for others so it should be no problem.

**Comment by hayden-t** [comment]
this just looks like the existing recommended way to run as service :)
https://github.com/boatbod/op25/blob/master/op25/gr-op25_repeater/apps/op25-rx.service

**Comment by JoeyAbsi** [comment]
It is!
