### ISSUE TITLE
NBFM via rx.py ??

### ISSUE THREAD

**Issue by hayden-t** [boatbod/op25#68]
Is it possible to tune a nbfm channel without using the multi/trunk scripts, say via just rx.py ??

**Comment by boatbod** [comment]
Sorry, only multi_rx.py understands how to instantiate the nbfm module.  That said, there should be nothing you can do with rx.py that you can't duplicate with multi_rx.py using the far more extendable cfg.json  

In short, rx.py is old and clunky and I wish it would die quietly in it's sleep ;)
