### ISSUE TITLE
[QUESTION] Change Web-Interface's Background Color ?

### ISSUE THREAD

**Issue by trengking** [boatbod/op25#78]
this might sound funny, but can I actually change the background color of OP25's web interface?

I'm planning to change it a bit darker, but don't know how to do it nor what files should I change.

I'm using OP25 on rpi4 with LCD display, since I can't change the brightness of the LCD, it is shining like the sun, especially at night 😁

thanks in advance 👍

**Comment by hayden-t** [comment]
web interface code is here https://github.com/boatbod/op25/tree/master/op25/gr-op25_repeater/www/www-static

**Comment by hayden-t** [comment]
just put this in main.css

html{background:#919191;}

**Comment by trengking** [comment]
thank you very much, I really appreciate it 😊👍👏👏👏
