### ISSUE TITLE
Active TGID not showing on the System frequencies table & encryption muting

### ISSUE THREAD

**Issue by JoeyAbsi** [boatbod/op25#88]
Active TGID is not being shown in the Active TGID table (or sometimes shown but disappears). 
This issue is caused by the new update of OP25 (because it didn't happen before).

I am running this system https://www.radioreference.com/apps/db/?sid=8086 which is a P25 Phase II system.

When tuned to encrypted talkgroups, no audio is coming out although the  --nocrypt option is not enabled on the command line.
Is it normal and is there a way to not mute it?

**Comment by boatbod** [comment]
Default --crypt-behavior is "1", which means "stay on channel but mute the audio"
The three --crypt-behavior options are:
0 - do not mute encrypted audio (will sound like garbage)
1 - mute encrypted audio but remain on active tgid
2 - release encrypted tgid and skip using it for the next 4 seconds.

**Comment by JoeyAbsi** [comment]
Thanks! I got this working now.

Do you know what is possibly causing the talkgroup to not show in the Active TGID table?

**Comment by boatbod** [comment]
By "Active TGID Table" you mean on the terminal?
There is a 1 second interval between updates to the terminal (www or curses) so it's possible a short conversation would not be noticed quickly enough to get on the screen.  
You could turn logging up to "-v 5" which will then log all the 'set tgid' entries every time activity is seen on the system. All traffic should result in a 'set tgid' message, so the first thing to check is whether this is happening as expected.

Can you describe the circumstances and configuration in more detail.  Is this rx.py or multi_rx.py?

**Comment by JoeyAbsi** [comment]
Sorry I was talking about the web interface.

The conversations are sometimes short but most of the time they are 5-7 seconds. The talkgroup shows in the Active TGID table for 1 second then disappears although the conversation is ongoing. 

I did update the refresh rate of the GUI interface for 2 refresh updates/second, but I don't think this is causing the problem, because before I updated OP25 it worked correctly.

I am running rx.py in normal configuration (1 rtl-sdr dongle) so I don't think there should be a problem.

**Comment by boatbod** [comment]
My test system seems to behave as expected.  Perhaps you could switch to the 'dev' branch, pull & build the code then run at log level 5.  You should see a series of "set tgid=" and "clear tgid=" messages.  The minimum time between a set and clear for the same tgid should be 1.2 seconds.

Let me know what you see.
