### ISSUE TITLE
P25 Phase II Inverted Time Slots

### ISSUE THREAD

**Issue by JoeyAbsi** [boatbod/op25#91]
When decoding P25 Phase II Voice, OP25 inverts the time slots on the Active Talkgroup ID table: TS 0 is located at the right and TS 1 is located at the left of the table
It would make more sense if TS 0 was at the left and TS 1 at the right.

**Comment by boatbod** [comment]
Binary coding conventionally has MSB on left and LSB on right.  TS0 therefore should be shown on the right.
