### ISSUE TITLE
IMBE Frame 88bit instead of 144bit

### ISSUE THREAD

**Issue by dgruber826** [boatbod/op25#92]
Hey all,

I am running OP25 on Ubuntu 16.04 and piping it into Wireshark. I'm wondering if there is a way for OP25 to show the 88bit IMBE frames instead of the 144 bit frames. Basically looking to remove the error correction in each frame. Thanks

**Comment by boatbod** [comment]
OP25 already outputs the AMBE/IMBE codewords which are the input to the vocoder.  If you want to get deeper into the xMBE model parameters after they are decomposed you'll need to spend some time trawling through the source code.  Have fun!
