### ISSUE TITLE
Slight typo in swig CMakeLists file

### ISSUE THREAD

**Issue by Yinette** [boatbod/op25#97]
https://github.com/boatbod/op25/blob/081ae4db70f2e393433ffe47ed237024fe1e05d0/op25/gr-op25_repeater/swig/CMakeLists.txt#L24

Somehow only noticed this while trying to compile on Fedora, does not seem to bother Ubuntu last time I tried. Can make a PR if that's easier for you :)

**Comment by boatbod** [comment]
Corrected, thank you!
