### ISSUE TITLE
Volume offset based on talkgroups

### ISSUE THREAD

**Issue by JoeyAbsi** [boatbod/op25#99]
When listening to certain talkgroups, the volume is way too high.
Would it be possible to adjust the volume offset based on certain talkgroups?

There could be a 4th column in the tgid-tags.tsv file where the user can select the volume offset for a selected talkgroup.
In example, the default offset is 3 (sound is not lowered/amplified) and the user can select 0/1/2 to lower the volume or 4/5/6 to amplify it.
The volume offset could act as a gain control.

**Comment by boatbod** [comment]
While I have no intention of implementing a TG-specific volume feature, you might want to look at the audio processing which liquidsoap can apply to an op25 stream.  The example op25.liq includes compressions and normalization which has been developed and tuned by wgbecks for the exact you describe.
